-- 1. Atliq Exclusive's operating centers in APAC region 

SELECT 
    DISTINCT market
FROM
    dim_customer
WHERE
    customer = 'Atliq Exclusive' AND region = 'APAC';
    
 ---------------------------------------------------------------------------------------------------------------------------------

-- 2. Unique Product increase % in 2021 vs 2020 

WITH cte1 AS 
(
SELECT
	count(DISTINCT product_code) unique_products_2020 
FROM 
	fact_sales_monthly 
WHERE
	fiscal_year = 2020)
,
cte2 AS 
(
SELECT 
	count(distinct product_code) unique_products_2021 
FROM
	fact_sales_monthly 
WHERE
	fiscal_year = 2021)

SELECT
	*, ROUND((unique_products_2021 - unique_products_2020)*100/unique_products_2020, 2) pct_change
FROM 
	cte1 CROSS JOIN cte2 ;

---------------------------------------------------------------------------------------------------------------------------------

-- 3. Number of products in each segment

SELECT 
    segment, COUNT(DISTINCT product_code) product_count
FROM
    dim_product
GROUP BY 
	segment
ORDER BY 
	product_count DESC;

---------------------------------------------------------------------------------------------------------------------------------

-- 4. Unique Product increase in 2021 vs 2020 by each segment

WITH cte1 AS 
(
SELECT
	segment, count(DISTINCT s.product_code) product_count_2020
FROM 
	fact_sales_monthly s JOIN dim_product p USING(product_code)
WHERE 
	fiscal_year = 2020
GROUP BY 
	segment),
cte2 AS 
(
SELECT
	segment,count(DISTINCT s.product_code) product_count_2021
FROM 
	fact_sales_monthly s JOIN dim_product p USING(product_code)
WHERE
	fiscal_year = 2021
GROUP BY
	segment)

SELECT
	cte1.segment, product_count_2020, product_count_2021,
    (product_count_2021 - product_count_2020) difference
FROM
	cte1 JOIN cte2 USING (segment)
ORDER BY
	difference DESC;

---------------------------------------------------------------------------------------------------------------------------------

-- 5. products with the highest and lowest manufacturing cost

SELECT 
    P.product_code, product, manufacturing_cost
FROM
    dim_product P
        JOIN
    fact_manufacturing_cost m USING(product_code)
WHERE
    manufacturing_cost IN (
		(SELECT MAX(manufacturing_cost) FROM fact_manufacturing_cost) ,
		(SELECT MIN(manufacturing_cost) FROM fact_manufacturing_cost)
        )
ORDER BY
	manufacturing_cost DESC;

---------------------------------------------------------------------------------------------------------------------------------

-- 6. Top 5 customers who received an average high pre_invoice_discount_pct for FY21 in Indian market

SELECT 
    c.customer_code,
    customer,
    ROUND(AVG(pre_invoice_discount_pct) * 100, 2) Avg_discount_pct
FROM
    dim_customer c
        JOIN
    fact_pre_invoice_deductions p USING (customer_code)
WHERE
    market = 'india' AND fiscal_year = 2021
GROUP BY
	c.customer_code , customer
ORDER BY 
	Avg_discount_pct DESC
LIMIT 5;

---------------------------------------------------------------------------------------------------------------------------------

-- 7. Monthly gross sales generated by the customer 'Atliq Exclusive'

SELECT 
    MONTHNAME(s.date) Month,
    s.fiscal_year Year,
    SUM(gross_price * sold_quantity)/1000000 gross_sales_mln
FROM
    fact_gross_price g
        JOIN
    fact_sales_monthly s USING (product_code)
        JOIN
    dim_customer c USING (customer_code)
WHERE
    customer = 'Atliq Exclusive'
GROUP BY Month , Year
order by year;

---------------------------------------------------------------------------------------------------------------------------------

-- 8. which quarter of 2020 had the max total_sold_quantity

WITH CTE AS 
(
SELECT
	sold_quantity,
	CASE WHEN month(date) in (9,10,11) THEN "Q1"
	WHEN month(date) in (12,1,2) THEN "Q2"
	WHEN month(date) in (3,4,5) THEN "Q3"
	ELSE "Q4" 
	END Quarters
FROM
	fact_sales_monthly
WHERE
	fiscal_year = 2020
)
SELECT
	Quarters,
	concat(round(sum(sold_quantity)/1000000,2), " M") total_sold_quantity
FROM 
	CTE
GROUP BY Quarters;


---------------------------------------------------------------------------------------------------------------------------------

-- 9. Which channel had the highest gross sales in 2021 


WITH cte AS (
SELECT 
    c.channel,
    concat(ROUND(SUM(gross_price * sold_quantity) / 1000000,2), " M") gross_sales_mln
FROM
    fact_gross_price g
        JOIN
    fact_sales_monthly s USING (product_code)
        JOIN
    dim_customer c USING (customer_code)
WHERE
    s.fiscal_year = 2021
GROUP BY c.channel
)
SELECT 	
	*, 
	round(gross_sales_mln * 100/sum(gross_sales_mln) OVER(),2) percentage 
FROM cte
ORDER BY percentage DESC;

---------------------------------------------------------------------------------------------------------------------------------

-- 10. Top 3 products by highest sold_quantity in each division in FY21

WITH cte AS 
(
SELECT 
	division,
    category,
	product_code,
	product,
	sum(sold_quantity) total_sold_qty,
	DENSE_RANK() OVER(PARTITION BY division ORDER BY sum(sold_quantity) DESC) rank_order
FROM
	dim_product p 
		JOIN 
    fact_sales_monthly s USING(product_code)
WHERE
	s.fiscal_year = 2021 
GROUP BY
	division,category,product_code,product
)
SELECT *
FROM cte
WHERE rank_order <= 3 ;